{{- if .Values.openshift.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.fullname" (tuple . "-openshift-cluster-role-binding") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.fullname" (tuple . "-openshift-cluster-role") }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
