apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" (tuple . "-events-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  events.config: |
{{ tpl (.Files.Get "events-collector-config.yaml") . | fromYaml | toYaml | indent 8 }}