{{- if .Values.otel.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" (tuple . "-metrics-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
data:
  metrics.config: |
{{ tpl (.Files.Get "metrics-collector-config.yaml") . | fromYaml | toYaml | indent 8 }}
{{- end}}