{{- if .Values.otel.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-metrics-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  metrics.config: |
{{ tpl (.Files.Get "metrics-collector-config.yaml") . | fromYaml | toYaml | indent 8 }}

  logs_service.proto: |
{{ tpl (.Files.Get "proto/collector/logs/v1/logs_service.proto") . | indent 8 }}
  logs.proto: |
{{ tpl (.Files.Get "proto/logs/v1/logs.proto") . | indent 8 }}
  common.proto: |
{{ tpl (.Files.Get "proto/common/v1/common.proto") . | indent 8 }}
  resource.proto: |
{{ tpl (.Files.Get "proto/resource/v1/resource.proto") . | indent 8 }}
{{- end}}