{{- if or .Values.otel.logs.enabled .Values.otel.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" (tuple . "-node-collector-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
data:
  logs.config: |
{{- $main := tpl (.Files.Get "node-collector-config.yaml") . | fromYaml }}
{{- $extra := tpl (.Files.Get "node-collector-config-entity-discovery.yaml") . | fromYaml }}
{{ merge $main $extra | toYaml | indent 8 }}
{{- end }}
