apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" (tuple . "-values") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
    swo.cloud.solarwinds.com/config-type: values-config-map
  annotations:
{{ include "common.annotations" . | indent 4 }}
data:
  VALUES_YAML: |-
    {{- $filteredValues := .Values | deepCopy }}
    {{- $filteredOtel := get $filteredValues "otel" }}
    {{- $_ := unset $filteredOtel "api_token" }}
    {{- $_ := set $filteredValues "otel" $filteredOtel }}
{{ $filteredValues | toYaml | b64enc | indent 4 }}