apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
  annotations:
    test-annotation: "test-value"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    sidecar.opentelemetry.io/inject: "true"
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo 'test_metric_from_pod 1' > /metrics; httpd -f -p 8080 -h /; sleep infinity"]
    ports:
    - containerPort: 8080