// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("swk8sattributes")
	ScopeName = "github.com/solarwinds/swi-k8s-opentelemetry-collector/processor/swk8sattributesprocessor"
)

const (
	ProfilesStability = component.StabilityLevelDevelopment
	LogsStability     = component.StabilityLevelBeta
	MetricsStability  = component.StabilityLevelBeta
	TracesStability   = component.StabilityLevelBeta
)
