---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swi-opentelemetry-collector
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: swi-opentelemetry-collector
---
apiVersion: v1
kind: Service
metadata:
  name: swi-opentelemetry-collector
  labels:
    app: swi-opentelemetry-collector
spec:
  selector:
    app: swi-opentelemetry-collector
  ports:
    - protocol: TCP
      port: 4318
      targetPort: 4318
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: swi-opentelemetry-collector
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: swi-opentelemetry-collector
data:
  relay: |
    exporters:
      otlp:
        endpoint: ${OTEL_ENVOY_ADDRESS}
        tls:
          insecure: ${OTEL_ENVOY_ADDRESS_TLS_INSECURE}
        headers:
          "Authorization": "Bearer ${SOLARWINDS_API_TOKEN}"
    extensions:
      health_check: {}
      memory_ballast:
        size_mib: "204"

    processors:
      memory_limiter:
        check_interval: 5s
        limit_mib: 409
        spike_limit_mib: 128
      
      metricstransform:
        transforms:
          - include: ^(.*)$$
            match_type: regexp
            action: update
            new_name: k8s.$${1}
          - include: k8s.kube_namespace_status_phase
            action: update
            operations:
              - action: update_label
                label: phase
                new_label: sw.k8s.namespace.status
          - include: k8s.kube_pod_status_phase
            action: update
            operations:
              - action: update_label
                label: phase
                new_label: sw.k8s.pod.status
      groupbyattrs:
        keys:
          - node
          - exported_node
          - kubelet_version
          - provider_id
          - os_image
          - exported_namespace
          - pod
          - uid
          - pod_ip
          - host_ip
          - created_by_kind
          - created_by_name
          - host_network
          - priority_class
          - container_id
          - container
          - image
          - image_id
          - sw.k8s.pod.status
          - sw.k8s.namespace.status
      resource:
        attributes:
        # Remove useless attributes
        - key: service.name
          action: delete

        - key: host.name
          action: delete

        - key: port
          action: delete

        - key: scheme
          action: delete

        # Cluster
        - key: sw.k8s.cluster.uid
          value: ${CLUSTER_UID}
          action: insert

        - key: k8s.cluster.name
          value: ${CLUSTER_NAME}
          action: insert

        # Node
        - key: k8s.node.name
          from_attribute: node
          action: insert

        - key: host.id
          from_attribute: k8s.node.name
          action: insert
        
        - key: node
          action: delete

        - key: k8s.node.name
          from_attribute: exported_node
          action: upsert
        - key: exported_node
          action: delete

        - key: sw.k8s.node.version
          from_attribute: kubelet_version
          action: insert
        - key: kubelet_version
          action: delete

        - key: sw.k8s.node.provider.id
          from_attribute: provider_id
          action: insert
        - key: provider_id
          action: delete

        - key: sw.k8s.node.os.image
          from_attribute: os_image
          action: insert
        - key: os_image
          action: delete

        - key: host.id
          from_attribute: k8s.node.name
          action: insert

        # Namespace
        - key: k8s.namespace.name
          from_attribute: exported_namespace
          action: insert
        - key: exported_namespace
          action: delete

        # Pod
        - key: k8s.pod.name
          from_attribute: pod
          action: insert
        - key: pod
          action: delete

        - key: k8s.pod.uid
          from_attribute: uid
          action: insert
        - key: uid
          action: delete

        - key: sw.k8s.pod.ip
          from_attribute: pod_ip
          action: insert
        - key: pod_ip
          action: delete

        - key: sw.k8s.pod.host.ip
          from_attribute: host_ip
          action: insert
        - key: host_ip
          action: delete

        - key: sw.k8s.pod.createdby.kind
          from_attribute: created_by_kind
          action: insert
        - key: created_by_kind
          action: delete

        - key: sw.k8s.pod.createdby.name
          from_attribute: created_by_name
          action: insert
        - key: created_by_name
          action: delete

        - key: sw.k8s.pod.host.network
          from_attribute: host_network
          action: insert
        - key: host_network
          action: delete

        - key: sw.k8s.pod.priority_class
          from_attribute: priority_class
          action: insert
        - key: priority_class
          action: delete
        
        # Container
        - key: k8s.container.id
          from_attribute: container_id
          action: insert
        - key: container_id
          action: delete

        - key: k8s.container.name
          from_attribute: container
          action: insert
        - key: container
          action: delete

        - key: k8s.container.image.id
          from_attribute: image_id
          action: insert
        - key: image_id
          action: delete

        - key: k8s.container.image.name
          from_attribute: image
          action: insert
        - key: image
          action: delete

      batch:
        send_batch_size: 8192
        send_batch_max_size: 8192
        timeout: 1s
    receivers:
      prometheusremotewrite:
        protocols:
          http:
            endpoint: "localhost:4318"
      prometheus:
        config:
          scrape_configs:
            - job_name: prometheus
              scrape_interval: ${SCRAPE_INTERVAL}
              metrics_path: '/federate'
              params:
                'match[]':
                  - 'kube_pod_container_status_running'
                  - 'kube_pod_container_status_terminated'
                  - 'kube_pod_container_status_waiting'
                  - 'kube_pod_container_status_started'
                  - 'kube_pod_container_status_ready'
                  # - 'container_cpu_usage_seconds_total'
                  # - 'container_spec_cpu_quota'
                  # - 'container_spec_cpu_period'
                  # - 'container_memory_working_set_bytes'
                  # - 'container_spec_memory_limit_bytes'
                  # - 'kube_node_info'
                  # - 'kube_node_created'
                  # - 'kube_node_status_capacity'
                  # - 'kube_pod_created'
                  # - 'kube_pod_info'
                  # - 'kube_pod_start_time'
                  # - 'kube_pod_completion_time'
                  # - 'kube_pod_status_phase'
                  # - 'kube_pod_start_time'
                  # - 'kube_resourcequota'
                  # - '{__name__=~"kube_pod_container_.*"}'
              static_configs:
                - targets:
                  - ${PROMETHEUS_URL}
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        metrics:
          exporters:
          - otlp
          processors:
          - metricstransform
          - groupbyattrs
          - resource
          - memory_limiter
          - batch
          receivers:
          - prometheusremotewrite
          - prometheus
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: 0.0.0.0:8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swi-opentelemetry-collector
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: swi-opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/instance: swi-opentelemetry-collector
      component: standalone-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetry-collector
        app.kubernetes.io/instance: swi-opentelemetry-collector
        component: standalone-collector
    spec:
      serviceAccountName: swi-opentelemetry-collector
      securityContext: {}
      containers:
        - name: opentelemetry-collector
          command:
            - /swi-otelcol
            - --config=/conf/relay.yaml
          securityContext: {}
          image: "solarwinds/swi-opentelemetry-collector:latest"
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SOLARWINDS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: solarwinds-api-token
                  key: SOLARWINDS_API_TOKEN
                  optional: true
            - name: PROMETHEUS_URL
              value: "prometheus-server.monitoring.svc.cluster.local:80"
            - name: OTEL_ENVOY_ADDRESS
              value: "otel-collector.dc-01.st-ssp.solarwinds.com:443"
            - name: OTEL_ENVOY_ADDRESS_TLS_INSECURE
              value: "false"
            - name: SCRAPE_INTERVAL
              value: "60s"
            - name: CLUSTER_NAME
              value: "cluster name"
            - name: CLUSTER_UID
              value: "cluster-uid-123456789"
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: swi-opentelemetry-collector
            items:
              - key: relay
                path: relay.yaml
