{{- if and .Values.otel.metrics.enabled .Values.otel.metrics.autodiscovery.discovery_collector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" (tuple . "-prometheus-discovery-ta") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "common.fullname" (tuple . "-prometheus-discovery-ta") }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  selector:
    app: {{ include "common.fullname" (tuple . "-prometheus-discovery-ta") }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
{{- end }}
