name: 'Run Integration Tests'
description: 'Run pytest integration tests'
runs:
  using: 'composite'
  steps:
    - name: Run Integration tests
      run: |
        kubectl wait --for=condition=ready --timeout=60s pod -l app=timeseries-mock-service -n test-namespace

        # wait till vulnerability scans are finished
        echo "Waiting for vulnerability scans to complete"
        while true; do
            scans_count=$(kubectl get pods -n test-namespace -o name | grep -c "^pod/scan-vulnerabilityreport-" || true)
            if [[ $scans_count -eq 0 ]]; then
                break
            fi
            echo -n "."
            sleep 5
        done

        echo "Vulnerability scans completed"

        kubectl create job --from=cronjob/integration-test integration-test-manual -n test-namespace

        kubectl wait --for=condition=ready --timeout=60s pod -l job-name=integration-test-manual -n test-namespace
        kubetail -l job-name=integration-test-manual -n test-namespace &  

        # Wait for either complete or failed
        echo "Waiting for tests to complete"
        while true; do
            if kubectl wait --for=condition=complete --timeout=0 jobs/integration-test-manual -n test-namespace 2>/dev/null; then
                job_result=0
                break
            fi

            if kubectl wait --for=condition=failed --timeout=0 jobs/integration-test-manual -n test-namespace 2>/dev/null; then
                job_result=1
                break
            fi
            echo -n "."
            sleep 3
        done

        if [[ $job_result -eq 1 ]]; then            
          echo "Tests failed"
          exit 1
        fi

        echo "Tests succeeded"
      shell: bash
    - name: Collect logs on Failure
      id: collect-logs
      if: failure()
      shell: bash
      run: |
        mkdir pod-logs
        echo "Folder Created"
        pods=$(kubectl get pods -n test-namespace -o=jsonpath='{.items[*].metadata.name}')
        for pod in $pods; do
          containers=$(kubectl get pod $pod -n test-namespace -o=jsonpath='{.spec.containers[*].name}')
          for container in $containers; do
            echo "Logs for pod $pod, container $container:"               
            kubectl logs -n test-namespace $pod -c $container > pod-logs/$container.txt
          done
        done
        if [[ -f raw_bodies_dump.txt ]]; then
          mv raw_bodies_dump.txt pod-logs/
        fi
        touch pod-logs/.collected
        echo "Logs collected"
    - name: Upload pod logs
      uses: actions/upload-artifact@v4
      if: always() && steps.collect-logs.conclusion == 'success'
      with:
        name: pod-logs
        path: pod-logs/
        retention-days: 1
