name: 'Run Integration Tests'
description: 'Run pytest integration tests'
runs:
  using: 'composite'
  steps:
    - name: Run Integration tests
      run: |
        kubectl wait --for=condition=ready --timeout=60s pod -l app=timeseries-mock-service -n test-namespace

        echo "Running skaffold verify..."
        kubectl config set-context kind-kind
        if skaffold verify --build-artifacts /tmp/tags.json; then
            job_result=0
        else
            job_result=1
        fi

        if [[ $job_result -eq 1 ]]; then
            echo "Tests failed"
            mkdir pod-logs
            echo "Folder Created"
            pods=$(kubectl get pods -n test-namespace -o=jsonpath='{.items[*].metadata.name}')
            for pod in $pods; do
              containers=$(kubectl get pod $pod -n test-namespace -o=jsonpath='{.spec.containers[*].name}')
              for container in $containers; do
                echo "Logs for pod $pod, container $container:"               
                kubectl logs -n test-namespace $pod -c $container > pod-logs/$container.txt
              done
            done
            mv raw_bodies_dump.txt pod-logs/
            exit 1
        fi

        echo "Tests succeeded"
      shell: bash
    - name: Upload pod logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: pod-logs
        path: pod-logs/
        retention-days: 1
