name: 'Run Integration Tests'
description: 'Run pytest integration tests'
runs:
  using: 'composite'
  steps:
    - name: Run Integration tests
      run: |
        kubectl create job --from=cronjob/integration-test integration-test-manual -n test-namespace

        kubectl wait --for=condition=ready --timeout=60s pod -l job-name=integration-test-manual -n test-namespace
        kubetail -l job-name=integration-test-manual -n test-namespace &  

        # Wait for either complete or failed
        while true; do
            if kubectl wait --for=condition=complete --timeout=0 jobs/integration-test-manual -n test-namespace 2>/dev/null; then
                job_result=0
                break
            fi

            if kubectl wait --for=condition=failed --timeout=0 jobs/integration-test-manual -n test-namespace 2>/dev/null; then
                job_result=1
                break
            fi

            echo "Waiting for tests to complete"
            sleep 3
        done

        if [[ $job_result -eq 1 ]]; then
            echo "Tests failed"
            mkdir pod-logs
            echo "Folder Created"
            pods=$(kubectl get pods -n test-namespace -o=jsonpath='{.items[*].metadata.name}')
            for pod in $pods; do
              containers=$(kubectl get pod $pod -n test-namespace -o=jsonpath='{.spec.containers[*].name}')
              for container in $containers; do
                echo "Logs for pod $pod, container $container:"               
                kubectl logs -n test-namespace $pod -c $container > pod-logs/$container.txt
              done
            done

            exit 1
        fi

        echo "Tests succeeded"
      shell: bash
    - name: Upload pod logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: pod-logs
        path: pod-logs/
        retention-days: 1
