name: 'Deploy skaffold'
description: 'Deployes skaffold tool'
runs:
  using: 'composite'
  steps:
    - name: Setup skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.7.1/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
      shell: bash
    - name: Install Container Structure Test
      run: |
        wget -O container-structure-test https://storage.googleapis.com/container-structure-test/v1.14.0/container-structure-test-linux-amd64 && chmod +x container-structure-test
        sudo mv container-structure-test /usr/local/bin/
      shell: bash



