{{- if .Values.autoupdate.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.fullname" (tuple . "-autoupdate-role") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
{{- end }}