{{- if .Values.autoupdate.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.fullname" . }}-autoupdate-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.fullname" . }}-autoupdate-role
subjects:
- kind: ServiceAccount
  name: {{ include "common.fullname" . }}-autoupdate
{{- end }}