{{- if .Values.autoupdate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.fullname" (tuple . "-autoupdate") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
{{- end }}
