// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: testcommunicator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_testcommunicator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testcommunicator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_testcommunicator_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_testcommunicator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testcommunicator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_testcommunicator_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_testcommunicator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testcommunicator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_testcommunicator_proto_rawDescGZIP(), []int{2}
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Items         []string               `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_testcommunicator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testcommunicator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_testcommunicator_proto_rawDescGZIP(), []int{3}
}

func (x *DataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DataResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DataResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DataResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DataResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DataResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type TargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRequest) Reset() {
	*x = TargetRequest{}
	mi := &file_testcommunicator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRequest) ProtoMessage() {}

func (x *TargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testcommunicator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRequest.ProtoReflect.Descriptor instead.
func (*TargetRequest) Descriptor() ([]byte, []int) {
	return file_testcommunicator_proto_rawDescGZIP(), []int{4}
}

type TargetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	TargetHost     string                 `protobuf:"bytes,3,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort     int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	TargetResponse string                 `protobuf:"bytes,5,opt,name=target_response,json=targetResponse,proto3" json:"target_response,omitempty"`
	Timestamp      string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetResponse) Reset() {
	*x = TargetResponse{}
	mi := &file_testcommunicator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetResponse) ProtoMessage() {}

func (x *TargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testcommunicator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetResponse.ProtoReflect.Descriptor instead.
func (*TargetResponse) Descriptor() ([]byte, []int) {
	return file_testcommunicator_proto_rawDescGZIP(), []int{5}
}

func (x *TargetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TargetResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TargetResponse) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *TargetResponse) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TargetResponse) GetTargetResponse() string {
	if x != nil {
		return x.TargetResponse
	}
	return ""
}

func (x *TargetResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_testcommunicator_proto protoreflect.FileDescriptor

const file_testcommunicator_proto_rawDesc = "" +
	"\n" +
	"\x16testcommunicator.proto\x12\x10testcommunicator\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\r\n" +
	"\vDataRequest\"\xa4\x01\n" +
	"\fDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05items\x18\x04 \x03(\tR\x05items\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"\x0f\n" +
	"\rTargetRequest\"\xcd\x01\n" +
	"\x0eTargetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vtarget_host\x18\x03 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12'\n" +
	"\x0ftarget_response\x18\x05 \x01(\tR\x0etargetResponse\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp2\xfa\x01\n" +
	"\x10TestCommunicator\x12K\n" +
	"\x06Health\x12\x1f.testcommunicator.HealthRequest\x1a .testcommunicator.HealthResponse\x12H\n" +
	"\aGetData\x12\x1d.testcommunicator.DataRequest\x1a\x1e.testcommunicator.DataResponse\x12O\n" +
	"\n" +
	"CallTarget\x12\x1f.testcommunicator.TargetRequest\x1a .testcommunicator.TargetResponseB\tZ\a./protob\x06proto3"

var (
	file_testcommunicator_proto_rawDescOnce sync.Once
	file_testcommunicator_proto_rawDescData []byte
)

func file_testcommunicator_proto_rawDescGZIP() []byte {
	file_testcommunicator_proto_rawDescOnce.Do(func() {
		file_testcommunicator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testcommunicator_proto_rawDesc), len(file_testcommunicator_proto_rawDesc)))
	})
	return file_testcommunicator_proto_rawDescData
}

var file_testcommunicator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_testcommunicator_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: testcommunicator.HealthRequest
	(*HealthResponse)(nil), // 1: testcommunicator.HealthResponse
	(*DataRequest)(nil),    // 2: testcommunicator.DataRequest
	(*DataResponse)(nil),   // 3: testcommunicator.DataResponse
	(*TargetRequest)(nil),  // 4: testcommunicator.TargetRequest
	(*TargetResponse)(nil), // 5: testcommunicator.TargetResponse
}
var file_testcommunicator_proto_depIdxs = []int32{
	0, // 0: testcommunicator.TestCommunicator.Health:input_type -> testcommunicator.HealthRequest
	2, // 1: testcommunicator.TestCommunicator.GetData:input_type -> testcommunicator.DataRequest
	4, // 2: testcommunicator.TestCommunicator.CallTarget:input_type -> testcommunicator.TargetRequest
	1, // 3: testcommunicator.TestCommunicator.Health:output_type -> testcommunicator.HealthResponse
	3, // 4: testcommunicator.TestCommunicator.GetData:output_type -> testcommunicator.DataResponse
	5, // 5: testcommunicator.TestCommunicator.CallTarget:output_type -> testcommunicator.TargetResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testcommunicator_proto_init() }
func file_testcommunicator_proto_init() {
	if File_testcommunicator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testcommunicator_proto_rawDesc), len(file_testcommunicator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testcommunicator_proto_goTypes,
		DependencyIndexes: file_testcommunicator_proto_depIdxs,
		MessageInfos:      file_testcommunicator_proto_msgTypes,
	}.Build()
	File_testcommunicator_proto = out.File
	file_testcommunicator_proto_goTypes = nil
	file_testcommunicator_proto_depIdxs = nil
}
