# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Test for events-collector-config-map
templates:
  - events-collector-config-map.yaml
tests:
  - it: Events config should match snapshot when using default values
    template: events-collector-config-map.yaml
    asserts:
      - matchSnapshot:
          path: data
  - it: Events config should not contain manifest collection pipeline when disabled
    template: events-collector-config-map.yaml
    set:
      otel.manifests:
        enabled: false
    asserts:
      - matchSnapshot:
          path: data
  - it: Custom events filter with old syntax
    template: events-collector-config-map.yaml
    set:
      otel.events.filter:
        include:
          match_type: regexp
          record_attributes:
            - key: k8s.namespace.name
              value: ^.*$
    asserts:
      - matchSnapshot:
          path: data
  - it: Custom events filter with new syntax
    template: events-collector-config-map.yaml
    set:
      otel.events.filter:
        log_record:
          - not(IsMatch(resource.attributes["k8s.namespace.name"], "^.*$"))
    asserts:
      - matchSnapshot:
          path: data