# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Test for reducer-deployment
templates:
  - network/reducer-deployment.yaml
  - network/configmap.yaml
tests:
  - it: Deployment spec should match snapshot when ebpfNetworkMonitoring is enabled
    template: network/reducer-deployment.yaml
    set:
      ebpfNetworkMonitoring.enabled: true
    asserts:
      - matchSnapshot:
          path: spec.template.spec
  - it: Deployment should not be generated when ebpfNetworkMonitoring is disabled
    template: network/reducer-deployment.yaml
    set:
      ebpfNetworkMonitoring.enabled: false
    asserts:
      - hasDocuments:
          count: 0
