{{- if .Values.otel.metrics.autodiscovery.discovery_collector.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.fullname" (tuple . "-discovery-collector" 51) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "common.fullname" (tuple . "-discovery-collector" 51) }}
  minReplicas: {{ .Values.otel.metrics.autodiscovery.discovery_collector.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.otel.metrics.autodiscovery.discovery_collector.autoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.otel.metrics.autodiscovery.discovery_collector.autoscaler.targetCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.otel.metrics.autodiscovery.discovery_collector.autoscaler.targetMemoryUtilization }}
{{- end }}
