{{- if .Values.operator.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  mode: daemonset
  hostNetwork: true
  image: "{{ include "common.image" (tuple . .Values.otel "image" nil .Chart.AppVersion) }}"
  imagePullPolicy: {{ .Values.otel.image.pullPolicy }}
  securityContext: 
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
  config: |
{{ tpl (.Files.Get "node-collector-config.yaml") . | fromYaml | toYaml | indent 8 }}
{{- end }}