{{- if .Values.otel.metrics.autodiscovery.discovery_collector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.fullname" (tuple . "-ta-role") }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
  {{- if .Values.otel.metrics.autodiscovery.discovery_collector.installWithHelmHooks }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
  {{- end }}
{{ include "common.annotations" . | indent 4 }}
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - scrapeconfigs
      - probes
    verbs:
      - '*'
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
{{- end }}