{{- if and .Values.operator.enabled .Values.waitJobs.operator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-operator
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "common.fullname" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
        - name: wait-for-operator
          image: "{{ include "common.image" (tuple . .Values.waitJobs.operator (tuple "image" "waitjob_operator")) }}"
          imagePullPolicy: {{ .Values.waitJobs.operator.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              while [ "$(kubectl get pods -n {{ .Release.Namespace }} -l app.kubernetes.io/name=operator \
                -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}')" != "True" ]; do
                kubectl get pods -n {{ .Release.Namespace }} -l app.kubernetes.io/name=operator
                kubectl get pods -n {{ .Release.Namespace }} -l app.kubernetes.io/name=operator -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}'
                echo "Waiting for opentelemetry-operator to be ready..."
                sleep 5
              done
      restartPolicy: Never
  activeDeadlineSeconds: 300
  backoffLimit: 4
{{- end }}