name: Build and Test

on:
  push:
    branches:
      - chart-releaser-*

  pull_request:
    branches: [gh-pages]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v3
