name: Integration tests

on:
  push:
    branches:
      - feature/NH-40615-test-kubespray

jobs:
  vagrant-up:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
  
      - name: Run vagrant up
        run: vagrant up
        working-directory: tests/integration/kubespray
  
      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
        working-directory: tests/integration/kubespray
